version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3000:80
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

volumes:
  db-data: